# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/jid/jid.go
  ldflags:
  - -s -w
  goos:
    - windows
    - openbsd
    - netbsd
    - linux
    - freebsd
    - darwin
  goarch:
    - arm64
    - amd64
    - 386
archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: zip
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
# for Validation
#release:
#  disable: true
