# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/jid/jid.go
    ldflags:
      - -s -w
    goos:
      - windows
      - openbsd
      - netbsd
      - linux
      - freebsd
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [zip]
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# for Validation
#release:
#  disable: true
