version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
  release:
    docker:
      - image: cimg/go:1.22
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:GdKQCwd1f2HsJKRbKm/HBBV6OLVzAfzE1E07od2mRN4"
      - checkout
      - run:
          name: build jid using goreleaser
          command: curl -sfL https://goreleaser.com/static/run | bash
workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
